services:
  # Flask Backend
  - type: web
    name: asl-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: "*"

  # React Frontend
  - type: web
    name: asl-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://asl-backend.onrender.com
